global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: 'flask'
    metrics_path: '/metrics'
    static_configs:
    - targets: ['127.0.0.1:5000']
